#! /bin/sh

if test $# -ne 1
then
	echo Usage: $0 INDEX
	exit 1
fi

ip netns add application$1
ip netns add tcpr$1

ip link add application$1 address 0:0:0:0:$1:3 type veth peer name gateway netns tcpr$1 address 0:0:0:0:$1:4
ip link set application$1 up

ip netns exec application$1 sh <<END
ip link add eth0 address 0:0:0:0:$1:1 type veth peer name application$1 netns tcpr$1 address 0:0:0:0:$1:2
ip link set lo up
ip link set eth0 up
ip address add 192.168.$1.1/24 dev eth0
ip route add default via 192.168.$1.3
END

ip netns exec tcpr$1 sh <<END
ip link add bridge type bridge
ip link set lo up
ip link set application$1 up
ip link set gateway up
ip link set bridge up
ip link set application$1 master bridge
ip link set gateway master bridge
ip address add 192.168.$1.2/24 dev bridge
ip route add default via 192.168.$1.3
END

modprobe tcpr
ip netns exec tcpr$1 iptables-restore <<END
*mangle
-A FORWARD -p udp -m physdev --physdev-in application$1 -j TCPR
-A FORWARD -p tcp -m physdev --physdev-in application$1 -j TCPR
-A FORWARD -p tcp -m physdev --physdev-out application$1 -j TCPR --peer
COMMIT
END

ovs-vsctl add-port gateway application$1
ip address add 192.168.$1.3/24 dev gateway
