#! /bin/sh

ip netns add peer

ip link add peer address 0:0:0:0:0:2 type veth peer name eth0 netns peer address 0:0:0:0:0:1
ip link set peer up

ip netns exec peer sh <<END
ip link set lo up
ip link set eth0 up
ip address add 192.168.0.1/24 dev eth0
ip route add default via 192.168.0.2
END

ovs-vsctl add-port gateway peer
ip address add 192.168.0.2/24 dev gateway
