#! /bin/sh

if test $# -ne 1
then
	echo Usage: $0 INDEX
	exit 1
fi

ip netns delete application$1
ip netns delete tcpr$1

ovs-vsctl del-port gateway application$1
ip address delete 192.168.$1.3/24 dev gateway
