#! /bin/sh

ip link delete application
ip link delete peer
ip netns delete application
ip netns delete peer
ip link set tcpr down
brctl delbr tcpr

iptables -t mangle -D FORWARD -m physdev --physdev-in application -p tcp -j TCPR
iptables -t mangle -D FORWARD -m physdev --physdev-in application -p udp -j TCPR
iptables -t mangle -D FORWARD -m physdev --physdev-out application -p tcp -j TCPR --peer
