#! /bin/sh

iptables -t mangle -D FORWARD -m physdev --physdev-in application -p tcp -j TCPR
iptables -t mangle -D FORWARD -m physdev --physdev-in application -p udp -j TCPR
iptables -t mangle -D FORWARD -m physdev --physdev-out application -p tcp -j TCPR --peer
rmmod tcpr
