#! /bin/sh

print_help() {
	echo "Usage: $0 [OPTIONS]"
	echo
	echo "Configure iptables for a TCPR application."
	echo
	echo "Options:"
	echo "  -p PORT  Let the application bind to PORT."
	echo "  -i HOST  Let the application bind to HOST."
	echo "  -e HOST  Let the peer connect to HOST."
	echo "  -?       Print this help message and exit."
	exit
}

while test $# -gt 0
do
	case "$1" in
	-i) i="$2"; shift 2;;
	-e) e="$2"; shift 2;;
	-p) p="$2"; shift 2;;
	-n) flush=":"; shift;;
	*) print_help;;
	esac
done

: ${i:=127.0.0.2}
: ${e:=127.0.0.1}
: ${p:=8888}
: ${flush:=iptables -F}

if test ! -e iptables.saved
then
	iptables-save > iptables.saved
fi

$flush
iptables -A INPUT -d $e/32 -p tcp --dport $p -j NFQUEUE
iptables -A OUTPUT -s $i/32 -p tcp --sport $p -j NFQUEUE
