#! /bin/sh

while test $# -gt 0
do
	case "$1" in
	-i) i="$2"; shift 2;;
	-e) e="$2"; shift 2;;
	-p) p="$2"; shift 2;;
	-n) flush=":"; shift;;
	esac
done

: ${i:=127.0.0.1}
: ${e:=127.0.0.2}
: ${p:=8888}
: ${flush:=iptables -F}

if test ! -e iptables.saved
then
	iptables-save > iptables.saved
fi

$flush
iptables -A INPUT -d $e/32 -p tcp --dport $p -j NFQUEUE
iptables -A OUTPUT -s $i/32 -p tcp --sport $p -j NFQUEUE
