#! /bin/sh

if test $# -gt 0
then
	echo "Usage: $0"
	echo
	echo "Restore iptables to its state before tcpr-setup-iptables."
fi

test -f iptables.saved &&
iptables-restore < iptables.saved &&
rm iptables.saved
